name: Preview example site

on:
    pull_request:
        types: [opened, reopened, synchronize, closed]

jobs:
    deploy-preview:
        uses: PazerOP/pr-preview-action/.github/workflows/preview.yml@v1
        with:
            source-dir: test/fixtures/sample
        secrets: inherit
